// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "opnctl1.h"

/////////////////////////////////////////////////////////////////////////////
// COpnctl1

IMPLEMENT_DYNCREATE(COpnctl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// COpnctl1 properties

/////////////////////////////////////////////////////////////////////////////
// COpnctl1 operations
